#!/usr/bin/env bash

TARGET=$(git describe --dirty --broken --all --long);
PROJECT=$(git config remote.origin.url |sed 's#.*\/\(.*\)\.git#\1#');

curl -i \
    -H "Content-Type:application/json" \
    -X POST \
    -d "{\"text\": \"deployed \`${PROJECT}\` \`$TARGET\` to \`$1\` \"}" \
    $2