#!/usr/bin/osascript

on run argv
	set message to item 1 of argv
	set targetBuddyPhone to item 2 of argv
    tell application "Messages"
        set targetService to 1st service whose service type = iMessage
        set targetBuddy to buddy targetBuddyPhone of targetService
        send message to targetBuddy
    end tell
end run